---
- name: Konfiguracja ogolna dla wszystkich hostow
  ignore_errors: true
  become: true
  vars: 
    do_undo: present
    share_name: share
    # ansible_python_interpreter: /usr/bin/python3
    
  
  hosts: 'all'

  tasks: 

    ### GRUPY ###
    - name: Grupa - tworzenie 
      group: 
        name: 'test_group'
        state: '{{ do_undo }}'

    ### UZYTKOWNICY ### 
    - name: User - tworzenie wymienionych 
      user: 
        name: '{{ item.name }}'
        create_home: true
        home: '/home/example_home/{{ item.name }}'
        groups: 
          '{{ item.groups }}'
        append: yes
        state: '{{ do_undo }}'
      loop:
          - { name: 'mariusz', groups: 'wheel, test_group' }
          - { name: 'test_user', groups: 'test_group' }

    ### UPDATE ###
    - name: Update
      dnf: 
        update_only: yes

    ### INSTALACJA ###
    - name: SERVICE - nfs i firewalld - instalacja 
      package: 
        name:
          - nfs-utils
          - firewalld
        state: '{{ do_undo }}'       
    
    ### SERVICE ###
    - name: SERVICE - nfs-client i firewalld - wlaczenie 
      service:
        name: '{{ item }}'
        state: started
        enabled: yes
      loop: 
        - nfs-client.target
        - firewalld

    #### SHARE ###
    - name: SHARE - tworzenie folderu do podmapowania
      file:
        path: /mnt/{{ share_name }}
        state: directory

    - name: SHARE - mapowanie udzialow nfs 
      mount: 
        path: /mnt/{{ share_name }}
        src: 192.168.1.50:/{{ share_name }}
        state: mounted
        fstype: nfs4
        opts: _netdev,rw,nofail
    
# DODAC CUSTOMOWE REPO DLA KAZDEGO SERWERA
   #  - name: SHARE - Kopia plikow .SHARE do /etc/yum.SHAREs.d
   #    copy: 
   #      src: /mnt/'{{ item }}'/'{{ item }}'.SHARE
   #      dest: /etc/yum.SHAREs.d/'{{ item }}'.SHARE
   #    loop: 
   #      - BaseOS
   #      - AppStream


    # REPO- wylaczenie domyslnych 
    # - name: REPO - Wylaczenie domyslnych repozytoriow 
    #   shell: sed -i "s/enabled=1/enabled=0/g" /etc/yum.repos.d/*