---
- name: Konfiguracja serwera ansible
  
  vars: 
    server_name: ansiblemachine
    # Wprowadzanie lub cofanie zmian
    do_undo: present
  
  hosts: '{{ server_name }}_group'
  become: true
  ignore_errors: true

  tasks:   

    # GRUPY
    - name: Grupa - tworzenie 
      group: 
        name: '{{ server_name }}group'
        state: '{{ do_undo }}'

    # UZYTKOWNIK 
    - name: User - tworzenie
      user: 
        name: '{{ server_name }}'
        create_home: true
        home: '/home/example_home/{{ server_name }}'
        groups: 
          - wheel
          - '{{ server_name }}group'
        append: yes
        state: '{{ do_undo }}'
         