---
- name: Konfiguracja serwera ansible
  vars_files: 
    - vars/reposerver_vars.yml
  
  hosts: '{{ server_name }}_group'
  become: true
  ignore_errors: true

  tasks:   

    # GRUPY
    - name: Grupa - tworzenie 
      group: 
        name: '{{ server_name }}group'
        state: '{{ do_undo }}'

    # UZYTKOWNIK 
    - name: User - tworzenie
      user: 
        name: '{{ user_to_add }}'
        create_home: true
        home: '/home/example_home/{{ user_to_add }}'
        groups: 
          '{{ user_groups }}'
        append: yes
        state: '{{ do_undo }}'
    
    # INSTALACJA DNF
    - name: '{{service_dnf_name}} - instalacja'
      package: 
        name: '{{service_dnf_name}}'
        state: '{{ do_undo }}'
    
    # SERVICE
    - name: '{{service_name}} - wlaczenie uslugi'
      service: 
        name: '{{service_name}}'
        state: started
        enabled: yes

    # FIREWALLD
    - name: 'Firewalld - odblokowanie {{ service_firewall_name }}'
      ansible.posix.firewalld:
        state: enabled
        permanent: yes
        immediate: yes
        service: '{{ service_firewall_name }}'
        