---
- name: Konfiguracja Dockerserver
  
  vars: 
    server_name: dockerserver
  
  hosts: dockerserver_group
  become: true
  ignore_errors: true
  
  tasks: 
    ### REPO docker ###
    - name: REPO - kopia pliku .repo dla dockera
      copy: 
        remote_src: yes
        src: /repos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo

    ### INSTALACJA dockera
    - name: INSTALACJA dockera
      package: 
        name: 
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    ### SERVICE
    - name: SERVICE - docker, start + enable
      service:
        name: docker
        state: started
        enabled: yes

    ### PIP 
    - name: PIP - pobranie modulu dla dockera
      pip: 
        name: docker

    # ### Docker - pobranie obrazu
    
    # Docker - dodanie DNSa do sieciowki 
    - name: Docker - dodanie DNSa
      shell: "nmcli con mod 'docker0' ipv4.dns 8.8.8.8"

    ### Docker - utworzenie kontenera
    - name: Docker - pobranie obrazu i utworzenie kontenera 
      docker_container: 
        image: httpd
        pull: yes
        name: httpd_ansible_cont
        volumes: 
          - /docker_data_host:/usr/local/apache2/htdocs
        published_ports: 8080:80

    # FIREWALLD
    - name: 'Firewalld - odblokowanie portu {{ service_port }} dla {{ service_name }}'
      ansible.posix.firewalld:
        state: enabled
        permanent: yes
        immediate: yes
        port: 8080/tcp
        
