---
- name: Konfiguracja ogolna
  hosts: all
  become: true

  vars_files: 
    - vars/webserver_vars.yml

  tasks:   

    - name: User - tworzenie
      user: 
        name: webserveruser
        state: present
    
    - name: Grupa - tworzenie 
      group: 
        name: webservergroup
        state: present
    
    - name: httpd - instalacja 
      package: 
        name: httpd
        state: present

    