---
- name: Konfiguracja webservera
  hosts: webserver_group
  vars: 
    server_name: webserver
    do_undo: present
    service_name: httpd
    service_port: 80
    service_port_protocol: tcp

  ignore_errors: true
  become: true
  
  tasks:   

    # GRUPY
    - name: Grupa - tworzenie 
      group: 
        name: '{{ server_name }}group'
        state: '{{ do_undo }}'

    # UZYTKOWNIK 
    - name: User - tworzenie
      user: 
        name: '{{ server_name }}'
        create_home: true
        home: '/home/example_home/{{ server_name }}'
        groups:
          wheel,{{ server_name }}group
        append: yes
        state: '{{ do_undo }}'

    # SERVICE
    - name: '{{service_name}} - instalacja'
      package: 
        name: '{{service_name}}'
        state: '{{ do_undo }}'

    # PODMIANA PLIKU INDEX
    - name: 'Podmiana pliku index.html'
      copy: 
        remote_src: yes 
        src: /web_data_host/index.html
        dest: /var/www/html/index.html

    - name: '{{service_name}} i firewalld - wlaczenie uslugi'
      service: 
        name: "{{ item }}"
        state: restarted
        enabled: yes
      loop: 
        - '{{service_name}}'
        - firewalld


    # FIREWALLD
    - name: 'Firewalld - odblokowanie portu {{ service_port }} dla {{ service_name }}'
      ansible.posix.firewalld:
        state: enabled
        permanent: yes
        immediate: yes
        port: '{{ service_port }}/{{ service_port_protocol }}'

