---
- name: Konfiguracja webservera
  ignore_errors: true
  vars_files: 
    - vars/webserver_vars.yml
  
  hosts: '{{ server_name }}_group'

# CONFIG HTTPD DO ZMIANY, SAMA ZMIANA PLIKU INDEX NIE WYSTARCZA

  tasks:   

    # GRUPY
    - name: Grupa - tworzenie 
      group: 
        name: '{{ server_name }}group'
        state: '{{ do_undo }}'

    # UZYTKOWNIK 
    - name: User - tworzenie
      user: 
        name: '{{ user_to_add }}'
        create_home: true
        home: '/home/example_home/{{ user_to_add }}'
        groups: 
          '{{ user_groups }}'
        append: yes
        state: '{{ do_undo }}'
    
    # SERVICE
    - name: '{{service_name}} - instalacja'
      package: 
        name: '{{ item }}'
        state: '{{ do_undo }}'
      loop:
        - '{{service_name}}'
        - firewalld
  
    - name: '{{service_name}} i firewalld - wlaczenie uslugi'
      service: 
        name: "{{ item }}"
        state: started
        enabled: yes
      loop: 
        - '{{service_name}}'
        - firewalld

    # FIREWALLD
    - name: 'Firewalld - odblokowanie portu {{ service_port }} dla {{ service_name }}'
      ansible.posix.firewalld:
        state: enabled
        permanent: yes
        immediate: yes
        port: '{{ service_port }}/{{ service_port_protocol }}'

    # PODMIANA PLIKU INDEX
    - name: 'Podmiana pliku index.html'
      copy: 
        src: /web_data_host/index.html
        dest: /etc/www/html/index.html

