---
- name: Konfiguracja webservera
  hosts: webservers
  become: true

  tasks: 

    - name: User - tworzenie 
      user: 
        name: webserveruser
        state: present
    
    - name: Grupa - tworzenie 
      group: 
        name: webservergroup
        state: present
    

    # - name: httpd - instalacja uslugi
    # - name: httpd - wlaczenie uslugi